### ISSUE TITLE
MainActivity is not called after changing the Target Framework to Android 10

### ISSUE THREAD

**Issue by Aniiia** [msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps#18] opened 2022-03-08 11:51 UTC
# Functional Issue Report
After changing the "Compile using Android Version (Target Framework)" to Android 10, the app will be installed on device, but the MainActivity is not shown (it is not called). We only see a white screen.

### Taskr Application Type
*TaskrForms.Android (your sample project of this repository)*

### Description
*A clear and concise description of what the issue is.*

### Repro Steps
*Steps to reproduce the behavior.*

1. Download Taskr-Project from this repository
2. Adapt ClientID in Manifest-File and in ClientID + RedirectURI in Authenticator-Class
3. Run Project "TaskrForms.Android" in "Release" mode for a real device
4. All is good, the user can login

Now, please do the following:

1. open "Options" of "TaskrForms.Android": go to "Build/General" and set the "Compile using Android Version (Target Framework)" to Android 10
2. make "Run" "TaskrForms.Android" => failed
3. added missing Nuget-Packages to .csproj of "TaskrForms.Android":

- Xamarin.AndroidX.ConstraintLayout Version="1.1.3.1"
- Xamarin.AndroidX.Emoji.AppCompat Version="1.0.0.1"
- Xamarin.AndroidX.Leanback Version="1.0.0.1"

5. "restore" Nuget-Packages
6. make "Run" "TaskrForms.Android" => failed
7. added missing Nuget-Package
- Xamarin.AndroidX.AppCompat.Resources` (i added version 1.1.0)
8. "restore" Nuget-Packages
9. make "run" "TaskrForms.Android" => App is installed on device, but the MainActivity is not shown (it is not called), so we only see a white screen.

### Expected Behavior
*Run of the app should not end up in showing a white screen. The user should be able to login.*

### Application Output
[NetworkSecurityConfig] No Network Security Cem) Binder:2195_3 expire 7 lines
[libc] SetHeapTaggingLevel: tag level set to 0
[_Intune_MAMtes] Not starting debugger since process cannot load the jdwp agent.
[ApplicationLoaders] Returning zygote-cached class loader: /system/framework/android.test.base.jar
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[MAMInfo] MAMInfo initialized. Debug=false, UseTestAgent=false, ManagedDialogDisabled=false, DeprecationDialogDisabled=false, PolicyRequired=false, MultiIdentityEnabled=false, FullBackupContent=true, UseDefaultEnrollment=false, ExceptionOnInit=false, Debuggable=false
[_Intune_MAMtes] The ClassLoaderContext is a special shared library.
[_Intune_MAMtest] type=1400 audit(0.0:6517): avc: granted { execute } for path="/data/user/0/net.customer.SampleApp/mam_libs/arm64-v8a/libunwind.so" dev="dm-12" ino=42980 scontext=u:r:untrusted_app_27:s0:c146,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c146,c257,c512,c768 tclass=file app=net.customer.SampleApp
[_Intune_MAMtest] type=1400 audit(0.0:6518): avc: granted { execute } for path="/data/user/0/net.customer.SampleApp/mam_libs/arm64-v8a/libmsmam-pre.so" dev="dm-12" ino=43090 scontext=u:r:untrusted_app_27:s0:c146,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c146,c257,c512,c768 tclass=file app=net.customer.SampleApp
[_Intune_MAMtest] type=1400 audit(0.0:6519): avc: granted { execute } for path="/data/user/0/net.customer.SampleApp/mam_libs/arm64-v8a/aes/libwolfssl.so" dev="dm-12" ino=33664 scontext=u:r:untrusted_app_27:s0:c146,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c146,c257,c512,c768 tclass=file app=net.customer.SampleApp
[_Intune_MAMtest] type=1400 audit(0.0:6520): avc: granted { execute } for path="/data/user/0/net.customer.SampleApp/mam_libs/arm64-v8a/libmsmdmarp.so" dev="dm-12" ino=22248 scontext=u:r:untrusted_app_27:s0:c146,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c146,c257,c512,c768 tclass=file app=net.customer.SampleApp
[_Intune_MAMtest] type=1400 audit(0.0:6521): avc: granted { execute } for path="/data/user/0/net.customer.SampleApp/mam_libs/arm64-v8a/liborigin.so" dev="dm-12" ino=46916 scontext=u:r:untrusted_app_27:s0:c146,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c146,c257,c512,c768 tclass=file app=net.customer.SampleApp
[SQLiteCompatibilityWalFlags] Cannot read global setting sqlite_compatibility_wal_flags - Application state not available
[_Intune_MAMtest] type=1400 audit(0.0:6522): avc: denied { search } for name="vendor" dev="tmpfs" ino=14346 scontext=u:r:untrusted_app_27:s0:c146,c257,c512,c768 tcontext=u:object_r:mnt_vendor_file:s0 tclass=dir permissive=0 app=net.customer.SampleApp
[monodroid-gc] GREF GC Threshold: 46080
[AdrenoGLES-0] QUALCOMM build                   : 436a040394, Ie3251bda9d
[AdrenoGLES-0] Build Date                       : 10/14/20
[AdrenoGLES-0] OpenGL ES Shader Compiler Version: EV031.32.02.06
[AdrenoGLES-0] Local Branch                     : 
[AdrenoGLES-0] Remote Branch                    : 
[AdrenoGLES-0] Remote Branch                    : 
[AdrenoGLES-0] Reconstruct Branch               : 
[AdrenoGLES-0] Build Config                     : S P 10.0.7 AArch64
[AdrenoGLES-0] Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
[AdrenoGLES-0] PFP: 0x016ee190, ME: 0x00000000

### Device Information
 - Moto g10
 - Android 11

### Xamarin Information
Visual Studio Community 2019 for Mac
Version 8.10.19 (build 2)
Installation UUID: 9de7c9a2-34fc-4c38-986e-23d0061f7eba
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

### Screenshots and Video
![Screenshot_20220308-124551](https://user-images.githubusercontent.com/7578403/157232280-42285118-75f3-4326-940f-9884a1fe538e.png)

**Comment by boyzhang-msft** [comment] 2022-03-15 20:35
This is a known issue tracked here: https://github.com/msintuneappsdk/intune-app-sdk-xamarin/issues/49. Closing this one and future updates will be posted on the main issue. Please feel free to reopen it if you believe this is a different issue.

**Comment by meghandaly** [comment] 2022-03-30 18:18
Closing as a duplicate of #11

**Closed by meghandaly** 2022-03-30 18:18 UTC
Labels: Duplicate
